/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControlConstancia;
import javax.swing.DefaultListModel;
import dominio.Alumno;
import modelo.IModeloVista;

/**
 *
 * @author adell
 */
public class FrameConstanciaPrincipal extends javax.swing.JFrame implements ISuscriptor {

    /**
     * Creates new form FrameConstanciaPrincipal
     */
    public FrameConstanciaPrincipal() {
        initComponents();
        alumnosFiltradosJList.setModel(new DefaultListModel<String>());
    }
    private static FrameConstanciaPrincipal instancia;
    private ControlConstancia control = new ControlConstancia();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorPrincipalPanel = new javax.swing.JPanel();
        idTxTField = new javax.swing.JTextField();
        generarConstanciaBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        alumnosFiltradosJList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        contenedorPrincipalPanel.setBackground(new java.awt.Color(161, 79, 126));
        contenedorPrincipalPanel.setName(""); // NOI18N

        idTxTField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idTxTFieldKeyReleased(evt);
            }
        });

        generarConstanciaBtn.setText("Generar Constancia");
        generarConstanciaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarConstanciaBtnActionPerformed(evt);
            }
        });

        alumnosFiltradosJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        alumnosFiltradosJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alumnosFiltradosJListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(alumnosFiltradosJList);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.setBackground(new java.awt.Color(188, 124, 146));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setText("CONSTANCIAS");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Escribe tu id:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        javax.swing.GroupLayout contenedorPrincipalPanelLayout = new javax.swing.GroupLayout(contenedorPrincipalPanel);
        contenedorPrincipalPanel.setLayout(contenedorPrincipalPanelLayout);
        contenedorPrincipalPanelLayout.setHorizontalGroup(
            contenedorPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorPrincipalPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(contenedorPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorPrincipalPanelLayout.createSequentialGroup()
                        .addGroup(contenedorPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(contenedorPrincipalPanelLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idTxTField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(contenedorPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(generarConstanciaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        contenedorPrincipalPanelLayout.setVerticalGroup(
            contenedorPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorPrincipalPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(contenedorPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorPrincipalPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(generarConstanciaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenedorPrincipalPanelLayout.createSequentialGroup()
                        .addGroup(contenedorPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idTxTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPrincipalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPrincipalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generarConstanciaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarConstanciaBtnActionPerformed
        int indexSeleccionado = alumnosFiltradosJList.getSelectedIndex();

        if (indexSeleccionado == -1) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Por favor, seleccione un alumno de la lista.",
                    "Selección Requerida",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
        } else {

            control.seleccionarAlumnoPorIndice(indexSeleccionado);
            control.generarConstancia();
        }
    }//GEN-LAST:event_generarConstanciaBtnActionPerformed

    private void idTxTFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTxTFieldKeyReleased
        // TODO add your handling code here:
        String id = idTxTField.getText();

        control.filtrar(id);

    }//GEN-LAST:event_idTxTFieldKeyReleased

    private void alumnosFiltradosJListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alumnosFiltradosJListMouseClicked
        // TODO add your handling code here:
        int index = alumnosFiltradosJList.getSelectedIndex();

        if (index != -1) {
            control.seleccionarAlumnoPorIndice(index);
        }
    }//GEN-LAST:event_alumnosFiltradosJListMouseClicked

    public static FrameConstanciaPrincipal getInstancia() {
        if (instancia == null) {
            instancia = new FrameConstanciaPrincipal();
        }
        return instancia;
    }

    @Override
    public void update(IModeloVista modeloVista) {
        int indicePrevio = alumnosFiltradosJList.getSelectedIndex();

        DefaultListModel<String> listModel = new DefaultListModel<>();
        for (Alumno a : modeloVista.getAlumnosEncontrados()) {
            listModel.addElement(a.getNombre() + " [" + a.getId() + "]");
        }

        this.alumnosFiltradosJList.setModel(listModel);

        if (indicePrevio != -1 && indicePrevio < listModel.getSize()) {
            alumnosFiltradosJList.setSelectedIndex(indicePrevio);
        }

        if (!modeloVista.getConstanciaTexto().isEmpty()) {
            this.jTextArea1.setText(modeloVista.getConstanciaTexto());
        } else if (modeloVista.getAlumnoSeleccionado() != null) {
            this.jTextArea1.setText(formatearFichaAlumno(modeloVista.getAlumnoSeleccionado()));
        } else {
            this.jTextArea1.setText("\n  Seleccione un alumno de la lista.");
        }
    }

    private String formatearFichaAlumno(Alumno sel) {
        if (sel == null) {
            return "";
        }

        return "  DETALLES DEL ALUMNO SELECCIONADO\n"
                + "  ====================================\n\n"
                + String.format("  %-10s %s\n", "ID:", sel.getId())
                + String.format("  %-10s %s\n", "NOMBRE:", sel.getNombre())
                + String.format("  %-10s %s\n", "CARRERA:", sel.getCarrera())
                + String.format("  %-10s %d° Semestre\n", "SEMESTRE:", sel.getNumeroSemestre())
                + String.format("  %-10s %d inscritas\n\n", "MATERIAS:", sel.getCantidadMaterias())
                + "  ------------------------------------\n"
                + "  Presione 'Generar Constancia' para el documento oficial.";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> alumnosFiltradosJList;
    private javax.swing.JPanel contenedorPrincipalPanel;
    private javax.swing.JButton generarConstanciaBtn;
    private javax.swing.JTextField idTxTField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
